server:
  port: 443
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store: classpath:javabegin_ssl.p12
    key-store-password: root
  http2:
    enabled: true

last.fm:
  api-token: "key"

steam:
  id: "id"
  api-token: "key"

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: pass
#    url: jdbc:postgresql://localhost:2346/visitor-db
    url:  jdbc:postgresql://visitor-db:5432/visitor-db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off