server:
  port: 80
#  ssl:
#    key-alias: gnaizel
#    key-store-type: PKCS12
#    key-password: pass
#    key-store: /etc/letsencrypt/live/gnaizel.online/keystore.p12
#  http2:
#    enabled: true
last.fm:
  api-token: "f8af34f52c1a0b81338eec49308b2e44"
logging:
  level:
    root: info
spring:
  main:
    banner-mode: off