server:
  port: 443
  ssl:
    key-alias: gnaizel
    key-store-type: PKCS12
    key-password: pass
    key-store: /etc/letsencrypt/live/gnaizel.online/keystore.p12
  http2:
    enabled: true
logging:
  level:
    root: info
spring:
  main:
    banner-mode: off