-- Гостевая книга. hidden — постмодерация: удаление прячет запись, а не стирает.
-- ip нужен только для лимитов, наружу он не отдаётся.
CREATE TABLE guestbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick VARCHAR(24),
    body VARCHAR(280) NOT NULL,
    ip VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE
);

-- лента читается по времени, лимиты считаются по паре ip + время
CREATE INDEX idx_guestbook_visible ON guestbook (hidden, created_at DESC);
CREATE INDEX idx_guestbook_ip ON guestbook (ip, created_at DESC);